services:
  # Development services
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: resonance
      POSTGRES_PASSWORD: "lJFLloEX4upcXtEis7c7zpMTFzIzjuxY"
    volumes:
      - resonance_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    ports:
      - "8091:6379"
    command: redis-server --requirepass "6T48csiH0HFJbWCpCHez-koZLgS7v3uk"
    environment:
      - REDIS_REPLICATION_MODE=master

  # Test services
  postgres_test:
    image: pgvector/pgvector:pg16
    ports:
      - "9090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: resonance_test
      POSTGRES_PASSWORD: "weBsKhSkNDrV3Wcbfjj-5NclQ3K7FVKY"
    volumes:
      - resonance_test_data:/var/lib/postgresql/data

  redis_test:
    image: redis:6.2.6
    ports:
      - "9091:6379"
    command: redis-server --requirepass "ovaEMeBWzAmz2zim1LaCAYMMClMO-TKm"
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  resonance_data:
  resonance_test_data:
