name: resonance_flutter
version: 1.0.0+1
publish_to: none
environment:
  sdk: ^3.8.0
  flutter: ^3.32.0
description: A new Flutter project with Serverpod.

dependencies:
  animated_text_kit: ^4.3.0
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.1.0
  flutter_svg: ^2.2.3
  flutter_web_plugins:
    sdk: flutter
  go_router: ^17.0.1
  google_fonts: ^7.1.0
  graphify:
    path: ./packages/graphify
  live_indicator: ^0.0.4
  mesh_gradient: ^1.3.8
  pointer_interceptor: ^0.10.1+2
  resonance_client:
    path: ../resonance_client
  riverpod_annotation: ^4.0.0
  serverpod_auth_idp_flutter: 3.2.1
  serverpod_flutter: 3.2.1
  url_launcher: ^6.3.2

dev_dependencies:
  build_runner: ^2.10.5
  custom_lint: ^0.8.1
  flutter_lints: ">=3.0.0 <7.0.0"
  flutter_test:
    sdk: flutter
  pubspec_dependency_sorter: ^1.0.5
  riverpod_generator: ^4.0.0+1
  riverpod_lint: ^3.1.0
  very_good_analysis: ^10.0.0
dependency_overrides:
  flutter_secure_storage: ^10.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/config.json
    - assets/svg/
